version: '2.1'
services:
  app:
    image: lambci/lambda:python3.8
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID- }
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY- }
      - AWS_DEFAULT_REGION=ap-northeast-1
      - REGION=ap-northeast-1
    volumes:
      - ./:/var/task
    command: >
      lambda_function.lambda_handler
      '{
        "inputs": [
          "静岡県浜松市天竜区春野町領家３３８－５",
          "埼玉県さいたま市南区別所６丁目１９－５－４０１"
        ]
      }'